version: '3.8'
services:
  postgres:
    image: bitnami/postgresql:15.1.0
    container_name: postgres
    environment:
      POSTGRESQL_USER: benchmark
      POSTGRESQL_PASSWORD: benchmark_pwd
      POSTGRESQL_REPLICATION_USER: benchmark_replica
      POSTGRESQL_REPLICATION_PASSWORD: benchmark_replica_pwd
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_DATABASE: benchmark
      POSTGRESQL_PGAUDIT_LOG: 'read, ddl'
    ports:
      - 5432:5432
  postgres-replica:
    container_name: postgres-replica
    image: bitnami/postgresql:15.1.0
    environment:
      POSTGRESQL_USER: benchmark
      POSTGRESQL_PASSWORD: benchmark_pwd
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_MASTER_HOST: postgres
      POSTGRESQL_REPLICATION_PORT_NUMBER: 5432
      POSTGRESQL_REPLICATION_USER: benchmark_replica
      POSTGRESQL_REPLICATION_PASSWORD: benchmark_replica_pwd
      POSTGRESQL_DATABASE: benchmark
    depends_on:
      - postgres
    ports:
      - 5433:5432
