version: '3.8'
services:
  postgres:
    build: ./master
    environment:
      POSTGRES_USER: cat_database
      POSTGRES_PASSWORD: cat_database
      POSTGRES_DB: cat_database
      PG_REP_USER: cat_database_replica
      PG_REP_PASSWORD: cat_database_replica_pwd
    ports:
      - 5432:5432
  postgres-replica:
    build: ./replica
    environment:
      POSTGRES_USER: cat_database
      POSTGRES_PASSWORD: cat_database
      POSTGRES_DB: cat_database
      PG_REP_USER: cat_database_replica
      PG_REP_PASSWORD: cat_database_replica_pwd
      PG_MASTER_HOST: postgres
    depends_on:
      - postgres
    ports:
      - 5433:5432
