DROP TABLE IF EXISTS cat_colors CASCADE;
DROP TABLE IF EXISTS cats CASCADE;
DROP TABLE IF EXISTS color_hex CASCADE;
DROP TABLE IF EXISTS house CASCADE;
DROP TABLE IF EXISTS toys CASCADE;
DROP TABLE IF EXISTS toys_producer CASCADE;
DROP TABLE IF EXISTS house_cats CASCADE;
DROP TABLE IF EXISTS toys_house CASCADE;
