DROP TABLE IF EXISTS cat_color CASCADE;
DROP TABLE IF EXISTS cat CASCADE;
DROP TABLE IF EXISTS color_hex CASCADE;
DROP TABLE IF EXISTS house CASCADE;
DROP TABLE IF EXISTS toy CASCADE;
DROP TABLE IF EXISTS toys_producer CASCADE;
DROP TABLE IF EXISTS house_cat CASCADE;
DROP TABLE IF EXISTS toy_house CASCADE;
