/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: +azNnSCAV/3N5Fnk5a9yC6jltI6w8uFz9VMw0ZfL6w7ewtdRFikzAHPDxJ9r+yMU8IMYUOIIJIa9uUvjlzDbWg==
 */

/* eslint-disable */
// tslint:disable

interface CatColor {
  color_name: string
  /**
   * @default nextval('cat_color_id_seq'::regclass)
   */
  id: number & { readonly __brand?: 'cat_color_id' }
}
export default CatColor

interface CatColor_InsertParameters {
  color_name: string
  /**
   * @default nextval('cat_color_id_seq'::regclass)
   */
  id?: number & { readonly __brand?: 'cat_color_id' }
}
export type { CatColor_InsertParameters }
