/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: pjq8xf8CR4Apfz5O2GXlOtUVjd2fFSw/HDC1hgP04hL3X9so1EW3XPQOm1V8ECMdVY5SjJq4Et9FszARjbHUKw==
 */

/* eslint-disable */
// tslint:disable

import CatColor from './cat_color'

interface ColorHex {
  hex_code: string
  id: CatColor['id']
}
export default ColorHex

interface ColorHex_InsertParameters {
  hex_code: string
  id: CatColor['id']
}
export type { ColorHex_InsertParameters }
