/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: mF2d+0m4W2jWkpgtmFbSDwOPpv3Eh6VARg+zVlhhgVh5SAX3t8oUnQ9oWpjFhLiLpT+CDE4CYD4myOOfwPjeQg==
 */

/* eslint-disable */
// tslint:disable

import Cat from './cat'
import House from './house'

interface HouseCat {
  cat_id: Cat['id']
  house_id: House['id']
}
export default HouseCat

interface HouseCat_InsertParameters {
  cat_id: Cat['id']
  house_id: House['id']
}
export type { HouseCat_InsertParameters }
