/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Q1IyGeg0USM308YS3YtnFVpTbUMBwksX4eDf6NmOu4Pylipt6TLOykpoUOaVwx8gJOeu/jsuV5A/9Mj9/YDUYw==
 */

/* eslint-disable */
// tslint:disable

interface House {
  has_dog: boolean | null
  house_address: string | null
  /**
   * @default nextval('house_id_seq'::regclass)
   */
  id: number & { readonly __brand?: 'house_id' }
}
export default House

interface House_InsertParameters {
  has_dog?: boolean | null
  house_address?: string | null
  /**
   * @default nextval('house_id_seq'::regclass)
   */
  id?: number & { readonly __brand?: 'house_id' }
}
export type { House_InsertParameters }
