/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: VcaX8XD3xt8wCsI00X6v7BMkxNI0np7TTYU3RKwHv7BbQxRwisO8BeJA+lULHwsjuNnP0AVA7rEp+D53n9pZzA==
 */

/* eslint-disable */
// tslint:disable

import Cat, { Cat_InsertParameters } from './cat'
import CatColor, { CatColor_InsertParameters } from './cat_color'
import ColorHex, { ColorHex_InsertParameters } from './color_hex'
import House, { House_InsertParameters } from './house'
import HouseCat, { HouseCat_InsertParameters } from './house_cat'
import Toy, { Toy_InsertParameters } from './toy'
import ToyHouse, { ToyHouse_InsertParameters } from './toy_house'
import ToysProducer, { ToysProducer_InsertParameters } from './toys_producer'

interface DatabaseSchema {
  cat: { record: Cat; insert: Cat_InsertParameters }
  cat_color: { record: CatColor; insert: CatColor_InsertParameters }
  color_hex: { record: ColorHex; insert: ColorHex_InsertParameters }
  house: { record: House; insert: House_InsertParameters }
  house_cat: { record: HouseCat; insert: HouseCat_InsertParameters }
  toy: { record: Toy; insert: Toy_InsertParameters }
  toy_house: { record: ToyHouse; insert: ToyHouse_InsertParameters }
  toys_producer: { record: ToysProducer; insert: ToysProducer_InsertParameters }
}
export default DatabaseSchema

/**
 * JSON serialize values (v) if the table name (t) and column name (c)
 * is a JSON or JSONB column.
 * This is necessary if you want to store values that are not plain objects
 * in a JSON or JSONB column.
 */
function serializeValue(t: string, c: string, v: unknown): unknown {
  if (t === 'toys_producer' && (c === 'hq_location' || c === 'stock_info')) {
    return JSON.stringify(v)
  }
  return v
}
export { serializeValue }

export type {
  Cat,
  CatColor,
  CatColor_InsertParameters,
  Cat_InsertParameters,
  ColorHex,
  ColorHex_InsertParameters,
  House,
  HouseCat,
  HouseCat_InsertParameters,
  House_InsertParameters,
  Toy,
  ToyHouse,
  ToyHouse_InsertParameters,
  Toy_InsertParameters,
  ToysProducer,
  ToysProducer_InsertParameters,
}
