/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 8BL6Emk8clBpskrAdnVKl76qvMlmWJq80Y/jp8oPfAg+VG2SLFj4yX5CkVjoJ7J1oLFLIMa3uP6ia55VDlIOTQ==
 */

/* eslint-disable */
// tslint:disable

import ToysProducer from './toys_producer'

interface Toy {
  barcode: string
  currency: string
  /**
   * @default now()
   */
  date_introduced: Date
  /**
   * @default nextval('toy_id_seq'::regclass)
   */
  id: number & { readonly __brand?: 'toy_id' }
  naughty: string | null
  price: string
  toy_name: string
  toys_producer_id: ToysProducer['id'] | null
}
export default Toy

interface Toy_InsertParameters {
  barcode: string
  currency: string
  /**
   * @default now()
   */
  date_introduced?: Date
  /**
   * @default nextval('toy_id_seq'::regclass)
   */
  id?: number & { readonly __brand?: 'toy_id' }
  naughty?: string | null
  price: string
  toy_name: string
  toys_producer_id?: ToysProducer['id'] | null
}
export type { Toy_InsertParameters }
