/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: t4A1SMuetkpsG4SsXlXCp6Le2LjDXsxGBC0W3oz0rw8yHvSULbtmYM1c0/2Lpav1LzYiAdqRR2pCUG6ZEqZSOg==
 */

/* eslint-disable */
// tslint:disable

import House from './house'
import Toy from './toy'

interface ToyHouse {
  /**
   * @default 1
   */
  amount: number
  house_id: House['id']
  toy_id: Toy['id']
}
export default ToyHouse

interface ToyHouse_InsertParameters {
  /**
   * @default 1
   */
  amount?: number
  house_id: House['id']
  toy_id: Toy['id']
}
export type { ToyHouse_InsertParameters }
