/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: DPeDZAZ3mqdj65eT1aesZotEl6G3zgwasZjiGJJjfRCCC2NnT1rMKHlIR/OxdG9YRdjsnvIgWT7dztIl3z6fuw==
 */

/* eslint-disable */
// tslint:disable

interface ToysProducer {
  hq_location: any
  /**
   * @default nextval('toys_producer_id_seq'::regclass)
   */
  id: number & { readonly __brand?: 'toys_producer_id' }
  stock_info: any
}
export default ToysProducer

interface ToysProducer_InsertParameters {
  hq_location: any
  /**
   * @default nextval('toys_producer_id_seq'::regclass)
   */
  id?: number & { readonly __brand?: 'toys_producer_id' }
  stock_info: any
}
export type { ToysProducer_InsertParameters }
